# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/generative_models',
                'doc_host': 'https://tobiasvanderwerff.github.io',
                'git_url': 'https://github.com/tobiasvanderwerff/generative_models',
                'lib_path': 'generative_models'},
  'syms': {'generative_models.core': {'generative_models.core.foo': ('core.html#foo', 'generative_models/core.py')}}}
