# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/generative_models',
                'doc_host': 'https://tobiasvanderwerff.github.io',
                'git_url': 'https://github.com/tobiasvanderwerff/generative_models',
                'lib_path': 'generative_models'},
  'syms': { 'generative_models.autoencoder': { 'generative_models.autoencoder.BabyAutoEncoder': ( 'autoencoder.html#babyautoencoder',
                                                                                                  'generative_models/autoencoder.py'),
                                               'generative_models.autoencoder.BabyAutoEncoder.__init__': ( 'autoencoder.html#babyautoencoder.__init__',
                                                                                                           'generative_models/autoencoder.py'),
                                               'generative_models.autoencoder.BabyAutoEncoder.calculate_loss': ( 'autoencoder.html#babyautoencoder.calculate_loss',
                                                                                                                 'generative_models/autoencoder.py'),
                                               'generative_models.autoencoder.BabyAutoEncoder.forward': ( 'autoencoder.html#babyautoencoder.forward',
                                                                                                          'generative_models/autoencoder.py')},
            'generative_models.data': {'generative_models.data.load_mnist': ('data.html#load_mnist', 'generative_models/data.py')}}}
