# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_autoencoder.ipynb.

# %% auto 0
__all__ = ['BabyAutoEncoder']

# %% ../nbs/00_autoencoder.ipynb 5
class BabyAutoEncoder(nn.Module):
    """Pretty much the simplest autoencoder you can imagine."""

    def __init__(self, n_in, n_latent, n_out):
        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(n_in, n_latent),
            nn.ReLU(inplace=True),
            nn.Linear(n_latent, n_out)
        )
    
    def forward(self, x):
        return self.model(x)

    def calculate_loss(self, x):
        ...  # TODO: reconstruction loss
